on:
  push:
    branches:
    - master

jobs:
  build-and-push:
    name: build and push docker image
    runs-on: ubuntu-22.04
    steps:
      - name: check list file
        run: ls -la
      - name: clone / download code
        uses: actions/checkout@v4
      - name: check list file
        run: ls -la
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
      - name: build docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: adhithia21/myapp-go:${{ github.run_number }}

  deploy:
    name: Deploy to server
    runs-on: ubuntu-22.04
    needs:
    - build-and-push
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            whoami
            ls -la
            docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
            docker pull adhithia21/myapp-go:${{ github.run_number }}
            docker rm -f myapp-go
            docker run --name myapp-go -d -p 80:3000 adhithia21/myapp-go:${{ github.run_number }}
